package ua.com.codefire.chat.ui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * Created by gmskov on 24.10.2016.
 */
public class Settings extends JFrame {

    private JFileChooser fileChooser;
    private JPanel settings;
    private JTextField newName;
    private JTextField path;
    private JButton saveButton;
    private JButton exitButton;

    public Settings() throws HeadlessException {
        setContentPane($$$getRootComponent$$$());
        pack();
        // Hook
        setLocationRelativeTo(null);
        setDefaultCloseOperation(HIDE_ON_CLOSE);


        exitButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                setVisible(false);
            }
        });


    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        settings = new JPanel();
        settings.setLayout(new GridLayoutManager(3, 2, new Insets(15, 15, 15, 15), -1, -1));
        settings.setMinimumSize(new Dimension(287, 50));
        settings.setPreferredSize(new Dimension(337, 100));
        newName = new JTextField();
        settings.add(newName, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        path = new JTextField();
        settings.add(path, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("New name:");
        settings.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Save history path:");
        settings.add(label2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JSplitPane splitPane1 = new JSplitPane();
        settings.add(splitPane1, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(200, 200), null, 0, false));
        exitButton = new JButton();
        exitButton.setMaximumSize(new Dimension(20, 10));
        exitButton.setPreferredSize(new Dimension(49, 10));
        exitButton.setText("Exit");
        splitPane1.setRightComponent(exitButton);
        saveButton = new JButton();
        saveButton.setMaximumSize(new Dimension(54, 10));
        saveButton.setMinimumSize(new Dimension(20, 10));
        saveButton.setPreferredSize(new Dimension(90, 10));
        saveButton.setText("Save");
        splitPane1.setLeftComponent(saveButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return settings;
    }
}

